src/views/about_view.py
from flask import Blueprint, render_template, redirect,url_for ,session

about_blueprint = Blueprint("about_view",__name__)

@about_blueprint.route("/about")
def about():
    return render_template("about.html", active="about")

@about_blueprint.route("/about/submitTicket", methods = ["POST"])
def submitTicket():
    return redirect(url_for("home_view.home"))

src/views/auth_view.py
from flask import Blueprint, render_template, send_file , url_for, redirect, request
from facades.auth_facade import AuthFacade
from models.client_error import *
from models.credentials_model import *
from utils.logger import Logger

auth_blueprint = Blueprint("auth_view",__name__)

facade = AuthFacade()

@auth_blueprint.route("/register",methods = ["GET","POST"])
def register():
    try:
        if request.method == "GET":return render_template("register.html",active = "register", user={})
        facade.register()
        return redirect(url_for("vacations_view.list"))
    except ValidationError as err:
        return render_template("register.html",error = err.message, user = err.model)
    

@auth_blueprint.route("/login",methods = ["GET","POST"])
def login():
    try:
        if request.method == "GET":return render_template("login.html", active="login", credentials = {})
        facade.login()
        return redirect(url_for("vacations_view.list"))
    except (ValidationError, AuthError) as err:
        Logger.log(err.message)
        return render_template("login.html",error = err.message, credentials = err.model)


@auth_blueprint.route("/logout")
def logout():
    facade.logout()
    return redirect(url_for("home_view.home"))

src/views/home_view.py
from flask import Blueprint, render_template, session , redirect, url_for
from facades.auth_facade import AuthFacade
home_blueprint = Blueprint("home_view",__name__)
auth_facade = AuthFacade()
from models.client_error import *
@home_blueprint.route("/")
@home_blueprint.route("/home")
def home():
    try:
        auth_facade.block_anonymous()
        user = session.get("current_user")
        return render_template("home.html", active="home", current_user = user)
    except AuthError as err:
       return redirect(url_for("auth_view.login",error=err.message, credentials = {}))
    except ValidationError as err:
        return render_template("login.html", error=err.message)

src/views/vacations_view.py
from flask import Blueprint, render_template, send_file , url_for, redirect, request, jsonify, session
from facades.vacation_facade import VacationFacade
from utils.image_handler import ImageHandler
from models.client_error import *
from facades.auth_facade import AuthFacade
from utils.logger import Logger
from facades.likes_facade import *
from models.role_model import RoleModel

vacation_blueprint = Blueprint("vacations_view",__name__)
facade = VacationFacade()
auth_facade = AuthFacade()
likes_facade = LikesFacade()


@vacation_blueprint.route("/vacations")
def list():
    try:
        auth_facade.block_anonymous()
        all_vacations = facade.get_all_vacations()
        current_user = session.get("current_user")
        liked_vacations = likes_facade.user_Likes_per_vacation(current_user["userId"])
        return render_template("vacations.html",vacations = all_vacations,likes = liked_vacations, active="vacations",user=RoleModel.User.value)
        
    except AuthError as err:
        return redirect(url_for("auth_view.login",error=err.message))
    except ValidationError as err:
        return render_template("login.html", error=err.message)


@vacation_blueprint.route("/vacations/images/<string:vacation_picture_file>")
def get_image(vacation_picture_file):
    image_path = ImageHandler.get_image_path(vacation_picture_file)
    return send_file(image_path)


@vacation_blueprint.route("/vacations/new", methods = ["GET","POST"])
def insert():
    try:
        auth_facade.block_non_admin()
        if(request.method=="GET"): return render_template("insert.html", active="new")
        facade.add_new_holiday()
        return redirect(url_for("vacations_view.list"))
    except AuthError as err:
        redirect("auth_view.login",error=err.message, credentials = {})
    except ValidationError as err:
        return render_template("insert.html", error=err.message)


@vacation_blueprint.route("/vacations/edit/<int:vacation_id>", methods = ["GET","POST"])
def edit(vacation_id):
    try:
        auth_facade.block_non_admin()
        if(request.method=="GET"): 
            one_vacation = facade.get_one_vacation(vacation_id)
            return render_template("edit.html", vacation = one_vacation)
    
        facade.update_vacation()
        return redirect(url_for("vacations_view.list"))
    except ValidationError as err:
        return render_template("edit.html", error=err.message) 

@vacation_blueprint.route("/vacations/delete/<int:vacation_id>")
def delete(vacation_id):
    try:
        auth_facade.block_non_admin()
        facade.delete_existing_vacation(vacation_id)
        return redirect(url_for("vacations_view.list"))
    except AuthError as err:
        all_vacations = facade.get_all_vacations()
        return render_template("home.html",error = err.message, vacations = all_vacations,admin=1)
    

@vacation_blueprint.route("/vacations/like_vacation/<int:vacation_id>", methods=["POST"])
def like_vacation(vacation_id):
    current_user = session.get("current_user")
    likes_facade.add_likes_to_vacations(current_user["userId"], vacation_id)
    new_like_count = likes_facade.get_likes_by_vacation_id(vacation_id)  # Fetch the updated like count
    return jsonify({"success": True, "message": "Liked vacation", "LikeCount": new_like_count}), 200


@vacation_blueprint.route("/vacations/unlike_vacation/<int:vacation_id>", methods=["POST"])
def unlike_vacation(vacation_id):
    current_user = session.get("current_user")
    likes_facade.remove_like_from_vacation(current_user["userId"], vacation_id)
    new_like_count = likes_facade.get_likes_by_vacation_id(vacation_id)  # Fetch the updated like count
    return jsonify({"success": True, "message": "Unliked vacation", "LikeCount": new_like_count}), 200

src/templates/about.html
{% extends "layout.html" %}


{% block content %}
 
        
        <div id="about" class="popup mfp-with-anim mfp-hide tm-bg-gray">
            <br>
            <h2 class="tm-about-col tm-mb-40 tm-page-title">
                 <span class="highlight-beach">BEACH <span class="highlight-vibes">vibes</span></span>
            </h2>
            <div class="tm-row tm-about-row">
                <div class="tm-col tm-about-col tm-about-left">                    
                    <img src="static/images/about.jpg" alt="Image" class="tm-mb-30">
                    <p class="tm-mb-40">
                        Beach Vibes is your ultimate travel partner for discovering the world’s most stunning beach vacations at unbeatable prices. We specialize in finding exceptional beach destinations with top-quality hotels that won’t break the bank. Our expert team scours the globe to bring you the best deals on beachfront getaways, ensuring a perfect blend of affordability and luxury. Whether you’re dreaming of a serene escape or an adventurous seaside retreat, Beach Vibes is dedicated to making your ideal beach vacation a reality. Let us transform your travel dreams into unforgettable experiences with the best value and exceptional quality.
                    </p>
                    
                </div>
                   
            </div>
        </div>

        <div id="contact" class="popup mfp-with-anim mfp-hide tm-bg-gray">
            <hr>
            <h2 class="tm-contact-col tm-color-primary tm-page-title tm-mb-40">Contact Us</h2>
            <div class="tm-row tm-contact-row">
                <div class="tm-col tm-contact-col">
                
                <!-- Do you need a working HTML contact form?
                    Please visit https://templatemo.com/contact page -->
                    
                    <form id="contact-form" action="{{ url_for('about_view.submitTicket') }}" method="POST" class="tm-contact-form">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control rounded-0" placeholder="Full Name" required />
                        </div>
                        <div class="form-group">
                            <input type="email" name="email" class="form-control rounded-0" placeholder="Email" required />
                        </div>
                        <div class="form-group">
                            <select class="form-control" id="contact-select" name="inquiry" required>
                                <option value="support">Customer support</option>
                                <option value="partnership">Partnership inquiries</option>
                                <option value="media">Media inquiries</option>
                                <option value="business">Business inquiries</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <textarea rows="8" name="message" class="form-control rounded-0" placeholder="Message" required=></textarea>
                        </div>
                        
                        <div class="form-group tm-text-center">
                            <button onclick="TicketSubmissionAlert()" type="submit" class="tm-btn tm-btn-primary" >Send it now</button>
                        </div>
                    </form>
                </div>
                <div class="tm-col tm-contact-col tm-contact-col-r">
                    <!-- Map -->
                    <div class="mapouter tm-mb-40">
                        
                        <hr>
                        <br>
                        <div class="gmap_canvas">
                            <iframe width="100%" height="520" id="gmap_canvas"
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3381.1755766576284!2d34.785012736028825!3d32.06449958523203!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151d4b70c925e5ed%3A0x9e629a46351e04c3!2sJohn%20Bryce%20Training!5e0!3m2!1sen!2sil!4v1722651108878!5m2!1sen!2sil" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"
                                frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    <br>

                    <!-- Address -->
                    <address class="tm-mb-40">
                        Khoma u-Migdal St 29, Tel Aviv-Yafo, 6777129<br>
                        <hr>

                        If you have any question's, feel free to contact us.
                    </address>
                    
                    <!-- Links -->
                    <ul class="tm-contact-links">
                        <li>
                            <a href="tel:0100200340">
                                <i class="fas fa-phone tm-contact-link-icon"></i>
                                Tel: 03-1381776
                            </a>
                        </li>
                        <li>
                            <a href="mailto:info@company.com">
                                <i class="fas fa-at tm-contact-link-icon"></i>
                                Email: BeachVibes@gmail.com
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <footer class="tm-footer icon-spacing3">
            <span>Copyright &copy; 2024 Beach Vibes</span>
        </footer>
    </div>
    
{% endblock content %}

src/templates/auth.html
<div>

    {% set current_user = session.get("current_user") %}




    {% if current_user %}
        <span> Hello {{current_user["firstname"]}} {{current_user["lastname"]}}</span>
        <span>|</span>
        <a href = "{{url_for('auth_view.logout') }}">Logout</a>


    {% else %}
        
        <span>Hello guest.</span>
        <span>|</span>
        <a href = "{{url_for('auth_view.login')}}">Login</a>
        <span>|</span>
        <a href = "{{url_for('auth_view.register')}}">Register</a>
        
    {% endif %}










</div>

src/templates/edit.html
{% extends "layout.html" %}

{% block content %}
<form method="post" class="fancy_form" enctype="multipart/form-data">
    <input type="hidden" value="{{vacation.vacation_id}}"  name="vacation_id" class="form-control">
    <br><br>
    <label>Insert country by ID here:</label>
    <input type="numbers" value="{{vacation.country_id}}" name="country_id" class="form-control" >
            Scroll down for country by ID:
        <select class="form-control" name="Countries" required>
                <option>  1 - United States of America</option>
                <option>  2 - France</option>
                <option>  3 - Croatia</option>
                <option>  4 - Greece</option>
                <option>  5 - Spain</option>
                <option>  6 - Maldives</option>
                <option>  7 - Brazil</option>
                <option>  8 - Thailand</option>
                <option>  9 - Bahamas</option>
                <option> 10 - Seychelle</option>
                <option> 11 - Australia</option>
                <option> 12 - Israel</option>
        </select>
    <br>
    <label>Description:</label>
    <textarea rows="8" value="{{vacation.vacation_details}}" name="vacation_details" class="form-control rounded-0"  required minlength="1" maxlength="30">{{vacation.vacation_details}}</textarea>
    <br>
    <label>Start date:</label>
    <input type="date" value="{{vacation.vacation_date_start}}" name="vacation_date_start" class="form-control" required >
    <br>
    <label>End date:</label>
    <input type="date" value="{{vacation.vacation_date_end}}" name="vacation_date_end" class="form-control" required >
    <br>
    <label>Price:</label>
    <input type="number" value="{{vacation.vacation_price}}" name="vacation_price" class="form-control" required min="1" max="10000">
    <br>
    <label>Location Image:</label>
    <input type="file"  name="image" accept="image/*" class="form-control">
    
    <button class ="btn btn-primary w-100">Update</button>
    <br>
</form>    
<br>
<br>
{% endblock content %}

src/templates/home.html
{% extends "layout.html" %}

{% block content %}


<div class = "homepageintro video-background" >
            <video autoplay muted loop>
                <source src="static/images/backgroundocean.mp4" type="video/mp4">
                
            </video>
            <div class="homecontent">
                <div class="tm-row tm-content-row">
                    <div class="homeintro">
                            <h2 class="tm-color-primary tm-page-title">
                                Introducing <span class="highlight-beach">BEACH</span> <span class="highlight-vibes">vibes</span>
                            </h2>
                            We're thrilled to have you here. Dive into our exclusive deals on sun-soaked getaways, and let us help you plan your perfect beach vacation. Whether you’re dreaming of white sandy shores or crystal-clear waters, we’ve got the best offers to make your escape unforgettable.
                            <br>
                            
                            <div>
                                Click 👉 <a href="{{url_for('vacations_view.list')}}"> HERE</a> 👈 to check our BEST offers!
                            Happy travels! 🏖️🌴
                            </div>
                    </div>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
                    
                    
</div>                
 
    <footer class="tm-footer font-size: icon-spacing3">
        Copyright &copy; Beach Vibes 2024
    </footer>

</div>
{% endblock content %}

src/templates/insert.html
{% extends "layout.html" %}


{% block content %}
    

    <form method="post" class="fancy_form" enctype="multipart/form-data">
        <h1 style="font-size: 30px;color: lightskyblue;">Add New Vacation:</h1>
        <br><br>
        <label>Insert Country by ID here:</label>
        <input type="numbers" name="country_id" class="form-control">
            <select class="form-control" name="Countries" required>
                    <option>  1 - United States of America</option>
                    <option>  2 - France</option>
                    <option>  3 - Croatia</option>
                    <option>  4 - Greece</option>
                    <option>  5 - Spain</option>
                    <option>  6 - Maldives</option>
                    <option>  7 - Brazil</option>
                    <option>  8 - Thailand</option>
                    <option>  9 - Bahamas</option>
                    <option> 10 - Seychelle</option>
                    <option> 11 - Australia</option>
                    <option> 12 - Israel</option>
            </select>
        <br>
        <label>Description:</label>
        <input type="textarea" rows="8" name="vacation_details" class="form-control"  required minlength="1" maxlength="30">
        <br>
        <label>Start date:</label>
        <input type="date" name="vacation_date_start" class="form-control" required>
        <br>
        <label>End date:</label>
        <input type="date" name="vacation_date_end" class="form-control" required>
        <br>
        <label>Price:</label>
        <input type="number" name="vacation_price" class="form-control" required min="1" max="10000">
        <br>
        <label>Location Image:</label>
        <input type="file" name="image" accept="image/*" class="form-control">
        
        <button class ="btn btn-primary w-100">Add</button>
    </form> 
    <br>  
    

{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/templatemo-ocean-vibes.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script defer src="{{ url_for('static',filename='js/main.js') }}"></script>

</head>
<body>
    <header class="tm-site-header">
        <h1 class="tm-mt-0 tm-mb-15"><span class="tm-color-primary">BEACH</span> <span class="tm-color-gold">vibes</span></h1>
        <em class="tm-tagline tm-color-light-gray">Catch the Waves, Live the Dream – Your Ultimate Beach Escape Awaits!</em>
    </header>

    <!-- Video banner 400 px height -->
     
    <div id="tm-video-container">
        <video autoplay muted loop id="tm-video">
            <source src="static/video/ocean-sea-wave-video.mp4" type="video/mp4">
        </video>  
    </div>
    
    <div class="layout">
        <header> 
            {% include "nav.html" %}
            {% if error %}<span class="error">{{error}}</span>{% endif %}
                
        </header>

        <main>
            {% block content %}

            
            {% endblock content %}
        </main>

    </div>

</body>

</html>

src/templates/login.html
{% extends "layout.html" %}



{% block content %}
    

<form method="post" class="fancy_form" >
    <h1 style="color: rgb(0, 123, 255); margin-left: 125px;">Login</h1>
    <br>
    <label>Email:</label>
    <input type="email" value = "{{credentials.email}}" name="email" class="form-control" required minlength="2" maxlength="30">
    <br>
    <label>Password:</label>
    <input type="password" value = "{{credentials.password}}" name="password" class="form-control" required minlength="2" maxlength="20">
    <br>
    
    <button class ="btn btn-primary w-100">login</button>
    <br><br>
    <p style="margin-left: 20px;">New here ? <a href="{{url_for('auth_view.register')}}">Sign up</a> and begin your journy! </p>
    
</form>
    
{% endblock content %}

src/templates/nav.html
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item" style="margin-left: 500px;margin-right: 20px;">
                    <a class="nav-link active" aria-current="page" href="{{url_for('home_view.home')}}">Home</a>
                  </li>
                  <li class="nav-item" style="margin-right: 20px;">
                    <a class="nav-link active" aria-current="page" href="{{url_for('vacations_view.list')}}">Vacations</a>
                  </li>
                  <li class="nav-item" style="margin-right: 20px;">
                    <a class="nav-link active" aria-current="page" href="{{url_for('about_view.about')}}">About</a>
                  </li>
                  {% if current_user.role_type == admin %}
                  <li class="nav-item" style="margin-right: 20px;">
                    <a class="nav-link active" aria-current="page" href="{{url_for('vacations_view.insert')}}">Add Vacation</a>
                  </li>
                  {% endif %}

            <div class="auth">
                {% include "auth.html" %}
            </div>
            
          </div>
        </div>
      </nav>

src/templates/register.html
{% extends "layout.html" %}


{% block content %}

<form method="post" class="fancy_form" >
    <h2 style="color: rgb(0, 123, 255); margin-left: 125px;">Register</h2>
    <br>
    <br>
    <label>First Name:</label>
    <input type="text" name="firstname" value = "{{user.firstname}}" class="form-control" required minlength="2" maxlength="20">
    <br>
    <label>Last Name:</label>
    <input type="text" name="lastname" value = "{{user.lastname}}" class="form-control" required minlength="2" maxlength="20">
    <br>
    <label>Email:</label>
    <input type="email" name="email" value = "{{user.email}}" class="form-control" required minlength="2" maxlength="30">
    <br>
    <label>Password:</label>
    <input type="password" name="password" value = "{{user.password}}" class="form-control" required minlength="2" maxlength="20">
    <br>
    
    <button onclick="AlertRegistration()" class ="btn btn-primary w-100" href="{{url_for('vacations_view.list')}}">Register</button>
    
    <br><br>
    <p style="margin-left: 110px;">Already a member?</p>
    <p2 style="margin-left: 150px;"><a href = "{{url_for('auth_view.login')}}">Login</a></p2>
</form>
    <br><br>
{% endblock content %}

src/templates/vacations.html
{% extends "layout.html" %}


{% set current_user = session.get("current_user") %}
{% block content %}
<div class="box">
    {%for v in vacations%}
    <div class="row">
        <div class="column">
            <div class="showcase">
                <div class="travel-card">
                    <div class="image">
                        <img src="{{ url_for('vacations_view.get_image',vacation_picture_file =( v.vacation_picture_file if v.vacation_picture_file else '---'))}}">
                    </div>
                    <div class="content">
                        
                        <label class="date"><i class="fa fa-calendar" aria-hidden="true"></i> {{v.vacation_date_start}}
                            - {{v.vacation_date_end}}</label>
                        <div class="country-description">
                            <p7 class ="p7">{{v.country_name}}</p7>
                        </div>
                        <p class="p">{{v.vacation_details}}</p> 

                        {% if current_user.role_type == user %}
                        <div class="price">
                            <button class="button">${{v.vacation_price}}</button>
                        </div>
                        {% endif %}
                        {% if current_user.role_type == admin %}
                            <div class="price2">
                                <a class="button" href="{{ url_for('vacations_view.edit', vacation_id=v.vacation_id) }}" ><i class="fa fa-pencil" style="font-size:24px"></i> Edit</a>
                                
                                <a class="button" onclick="confirmDelete()" href="{{ url_for('vacations_view.delete', vacation_id = v.vacation_id) }}"><i class="fa fa-trash-o" style="font-size:24px"></i> Delete</a>
                            </div>
                        {% endif %}
                    </div>
                    {% if current_user.role_type == user %}
                    <button class="button-favorite like-button {% if v.vacation_id in likes %} liked {% endif %}" data-vacation_id="{{ v.vacation_id }}">
                    <span class="countLikes">{{v.LikeCount}}</span>
                    {% if v.vacation_id in likes %}
                    <i class="fas fa-heart-o fa-heart icon-spacing"></i>
                    {% else %}
                    <i class="far fa-heart-o icon-spacing"></i>
                    {% endif %}
                    </button>
                    {% endif %}
                    

                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<footer class="tm-footer icon-spacing3">
    <span>Copyright &copy; 2024 Beach Vibes</span>
</footer>
{% endblock content %}